
/control/execute myQweakConfiguration.mac
/HallC/Visibility/HideHallFloor

#
# Create a scene handler and viewer
#
#/vis/open OGLIX 1280x1024-0+0
#/vis/open OIX 1000x1000-0+0
/vis/open OGLIQt 1000x1000-0+0

#
# Set camera properties
#
/vis/viewer/set/viewpointThetaPhi 100 0
# use the line below to see the top of the experiment
#/vis/viewer/set/viewpointThetaPhi 100 60

#/vis/viewer/panTo 0 8   
#/vis/viewer/zoom 12.0


#
# Override surface visualization properties
#
/vis/viewer/set/style surface
#/vis/viewer/set/style wireframe
/vis/viewer/set/hiddenEdge true
/vis/viewer/set/hiddenMarker true

#
# Color particles by name
#
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron white
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton magenta
/vis/modeling/trajectories/drawByParticleID-0/set proton magenta


#
# Draw detector
#
/vis/drawVolume

#
# Declare that trajectories and hits should be added to the scene
#
/vis/scene/add/trajectories
/vis/scene/add/hits

#
# Set visualization to accumulate many events into one picture
#
/vis/scene/endOfEventAction accumulate 100

/run/beamOn 5

